# Generated by Django 5.0.2 on 2024-03-02 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('main_calendar', models.BooleanField(default=False)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_available_date', models.DateField()),
                ('duration', models.DurationField()),
                ('expiry', models.DateField()),
                ('generate_jitsi_link', models.BooleanField(default=False)),
                ('current_date', models.DateTimeField(blank=True, null=True)),
                ('email_of_customer', models.EmailField(blank=True, max_length=200, null=True)),
                ('caldav_event_uid', models.CharField(blank=True, max_length=200, null=True)),
                ('guid', models.CharField(blank=True, max_length=200, null=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
