# Generated by Django 5.0.2 on 2024-03-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
