# Generated by Django 5.0.2 on 2025-02-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='parent_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
