# Generated by Django 5.2.5 on 2025-12-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_ticket_parent_ticket_ticket_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='timezone_of_customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
