# Generated by Django 5.2.5 on 2026-01-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_ticket_timezone_of_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='invitation_text',
            field=models.CharField(blank=True, default='', help_text='This text will be generated for easy copy-pasting into the invitation email. You can use #BOOKING_LINK# and #TICKET_NAME# as placeholders.', max_length=5000, null=True),
        ),
    ]
